
server:
    port: 9001

spring:
    application:
        name: DEPARTMENT-SVC
    h2:
        console:
            enabled: true
            path: /h2-ui
    datasource:
        url: jdbc:h2:mem:depdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        show-sql: true
        properties:
            hibernate: 
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    sql:
        init:
            platform: h2