apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudeureka
  namespace: spingproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudeureka
  template:
    metadata:
      labels:
        app: cloudeureka
    spec:
      containers:
        - name: eurekaapp
          image: adamcao/eurekaservice:1.0
          ports:
            - containerPort: 8761
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-svc
  namespace: spingproject
spec:
  selector:
    app: eurekaapp
  ports:
    - port: 8761
      targetPort: 8761
  type: ClusterIP
