apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouduser
  namespace: spingproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clouduser
  template:
    metadata:
      labels:
        app: clouduser
    spec:
      containers:
        - name: userapp
          image: adamcao/userservice:1.0
          ports:
            - containerPort: 9002
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: spingproject
spec:
  selector:
    app: userapp
  ports:
    - port: 9002
      targetPort: 9002
  type: ClusterIP
