apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudgateway
  namespace: spingproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudgateway
  template:
    metadata:
      labels:
        app: cloudgateway
    spec:
      containers:
        - name: gatewayapp
          image: adamcao/gatewayservice:1.0
          ports:
            - containerPort: 9191
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: spingproject
spec:
  selector:
    app: gatewayapp
  ports:
    - port: 9191
      targetPort: 9191
  type: NodePort
